name: Publish to NPM

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Publish package to npm
        id: npm-publish
        working-directory: .
        run: |
          npm pkg fix
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.XCSS_NPM_TOKEN }}

  publish-bin:
    name: Bin Publish Trigger
    runs-on: ubuntu-latest
    env:
      SOURCE_REPO: yshell-dev/xcss-source

    steps:
      - name: Checkout xcss-source (read-only)
        uses: actions/checkout@v3
        with:
          repository: ${{ env.SOURCE_REPO }}
          token: ${{ secrets.XCSS_REPO_CROSS }}

      - name: Trigger publish workflow on Parent Repo
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: ${{ env.SOURCE_REPO }}
          token: ${{ secrets.XCSS_REPO_CROSS }}
          event-type: trigger-publish
